### ISSUE TITLE
add mythic metals & alloy forgery

### ISSUE THREAD

**Issue by Abbie5** [woodiertexas/unofficial-quilt-smp-the-3rd#11]
https://modrinth.com/mod/mythicmetals
https://modrinth.com/mod/alloy-forgery

lots of new metals, alloys, tools, weapons & armour

some pieces of gear have unique effects, plus it adds a nuke ☢️

**Comment by stantios** [comment]
Love how both these mods integrate together, it looks so cool. I would be happy to add this mod

**Comment by woodiertexas** [comment]
I've heard from somewhere that mythic metals tends to conflict with some other mods.
