### ISSUE TITLE
add wilder wild

### ISSUE THREAD

**Issue by Abbie5** [woodiertexas/unofficial-quilt-smp-the-3rd#12]
https://modrinth.com/mod/wilder-wild

large biome mod, expands upon the 1.19 wild update

has some feature overlap with missing wilds

**Comment by EvieTheOwl** [comment]
Uses Terrablender so likely compatible with #7 as well. Love the improved biomes, The changes are subtle but it adds a lot.

**Comment by stantios** [comment]
New biomes, and I am in. I love when mods add unique biomes, makes exploration so much fun. The aspect of finding new blocks or ores and using them to make new tools or armour is great, So with that, I would be happy to add this mod.

**Comment by stantios** [comment]
Closed as it was marked as "won't add".
