### ISSUE TITLE
add ZsoltMolnarrr's "RPG Series" mods

### ISSUE THREAD

**Issue by Abbie5** [woodiertexas/unofficial-quilt-smp-the-3rd#16]
https://modrinth.com/mod/wizards
https://modrinth.com/mod/paladins-and-priests
https://modrinth.com/mod/gazebos
https://modrinth.com/mod/jewelry

simple & easy to use magic

**Comment by woodiertexas** [comment]
During testing, I noticed that these mods have a crapload of dependencies and that gazebos has a broken mod menu usage. https://mclo.gs/FgEEtHz

**Comment by stantios** [comment]
As much as these mods look great, they have a lot of dependencies which creates a mess to clean up if we ever want to remove them.

So with that, we have decided to not add this mod.
