### ISSUE TITLE
[Mod Request]: Amecs

### ISSUE THREAD

**Issue by Abbie5** [woodiertexas/unofficial-quilt-smp-the-3rd#18]
### What does the mod do?

improves keybinds
adds a search bar to the keybinds screen and allows you to use modifiers in keybinds

### Is this mod on Modrinth?

Yes

### Link to the mod

https://modrinth.com/mod/amecs

**Comment by stantios** [comment]
I like what this mod does and the functionality of it, but I do not like that it adds extra keybinds.

**Comment by woodiertexas** [comment]
Amecs is listed as an optional mod on the repo's readme.
