### ISSUE TITLE
[Mod Request]: Better Climbing

### ISSUE THREAD

**Issue by Abbie5** [woodiertexas/unofficial-quilt-smp-the-3rd#20]
### What does the mod do?

improves climbing

### Is this mod on Modrinth?

Yes

### Link to the mod

https://modrinth.com/mod/better-climbing

**Comment by stantios** [comment]
Interesting concept to climbing, reminds of a mod that adds similar functionality to climbing (forgot the name).

I would be happy to add this mod.
