### ISSUE TITLE
[Mod Request]: Exordium

### ISSUE THREAD

**Issue by Abbie5** [woodiertexas/unofficial-quilt-smp-the-3rd#22]
### What does the mod do?

improves overall game performance by decreasing gui and screens framerate

### Is this mod on Modrinth?

Yes

### Link to the mod

https://modrinth.com/mod/exordium

**Comment by stantios** [comment]
As much as this mod improves performance, it could cause issues with some mods and their GUI's so I wouldn't recommend adding this mod.

**Comment by stantios** [comment]
Closed as it was marked as "won't add".
