### ISSUE TITLE
Modify Snow! Real Magic! snow accumulate mechanic

### ISSUE THREAD

**Issue by EvieTheOwl** [woodiertexas/unofficial-quilt-smp-the-3rd#30]
This feature: `Snow layer will accumulate during snow storm!` is really annoying. It stops u from being able to walk around snow biomes easily without constantly jumping and seems to break some biome mods #7.

U should be able to disable in the config

**Comment by EvieTheOwl** [comment]
There seems to be another bug with this mod as well. It kind of removes the model of certain plants replacing them with a blank bounding box. Idk If if this is related to this specific config option but it should help prevent this in world generation at least

![2023-09-18_14 56 44](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/b28f103c-ebc1-4597-ac84-686d4e67e2be)

**Comment by woodiertexas** [comment]
"Snow Real Magic" was removed from the pack.
