### ISSUE TITLE
More Snow, Real Magic! Issues

### ISSUE THREAD

**Issue by EvieTheOwl** [woodiertexas/unofficial-quilt-smp-the-3rd#31]
Happens when cutting down any tree. I'm guessing the mod isn't able to properly handle removing the snow from the tree after it is cut down with the Falling Tree's mod

![2023-09-18_15 04 21](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/6475aa84-dfbe-491e-a11a-c877753c3412)

**Comment by woodiertexas** [comment]
"Snow Real Magic" was removed from the pack a little while ago.
