### ISSUE TITLE
Phillips Ruins generation for certain structures overhangs

### ISSUE THREAD

**Issue by EvieTheOwl** [woodiertexas/unofficial-quilt-smp-the-3rd#37]
![image](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/f88e0caf-23d7-4bcb-97b4-a62c76e1c8fb)

This happens quite a lot. Due to the size of certain structures they overhang terrain.

**Comment by woodiertexas** [comment]
Philips Ruins has been removed from the pack a little while ago.
