### ISSUE TITLE
Add Regions Unexplored & Promenade

### ISSUE THREAD

**Issue by EvieTheOwl** [woodiertexas/unofficial-quilt-smp-the-3rd#7]
**Reason**: Regions Unexplored is an incredible mod that adds over 80+ new biomes including caves! They all look really impressive as well. Promenade is also neat and adds capybara's :3. Also has really unique biomes.

**Compatibility**: Both work with the other biome mods in the pack such as Missing Wilds. Structures also form fine and the same separation between regions can be seen with continents installed. This makes sense since Continents states: `Continents is compatible with most worldgen data packs, including Terralith` and both these mods are essentially bundled like datapacks with custom blocks.

Both mods contain the appropriate common tags as well for wood types, dirt etc... 

<img width="569" alt="Screenshot 2023-09-16 at 13 59 02" src="https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/1349f8b8-eb86-459d-ba92-7dc235b9cb74">

## Pretty pictures

Explored the overworld and took these screenshots of the 2 mods. This is only a very small proportion of the biomes from regions unexplored.

### Regions Unexplored

![image](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/c7ca9877-c506-471d-a8d8-ef73cd366d6d)
![image](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/d335fc01-6b97-4aec-9bc5-4785b1bd3aa8)
![image](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/6c950252-65f6-4aef-9501-b20e32d664e0)
![image](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/b1b108a6-a803-4646-8fdd-5e12309cdbc1)
![image](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/e3ff011a-2b88-4394-b465-539183e15d47)
![image](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/41ec8de6-64d2-48ad-9415-caf2a149daf4)

### Promenade

![image](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/a3595ff4-bf02-4e18-b8ee-3e716efe0fc2)
![image](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/d148de35-5992-4501-bbc1-36cfc3c43e80)
![image](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/664e5324-99df-4795-a21c-c1f17731d945)
![image](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/a7de8b6b-bfd6-4165-8025-703ddd9760fa)

**Comment by EvieTheOwl** [comment]
Please note the pics I took here were before adding Continents. When Continents is added they get a bit bigger + more ocean between them

**Comment by EvieTheOwl** [comment]
## Compatible with
- Any mod that uses Terrablender (most of them atm). Includes Terralith.
- Most datapacks + structure mods. Nullscape will work as it's kind of a bundled datapack within a mod

## In-compatibilities
- BCLib. BetterEnd, BetterNether etc... Both these mods are inherently very unstable at the moment anyway tbh. Spoke to the Enderscape peeps and they want to drop support for BCLib for this reason.

**Comment by woodiertexas** [comment]
Regions Unexplored has a slight "incompat" with [snow real magic](https://modrinth.com/mod/snow-real-magic)
![image](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/17211100/5222d28e-1807-4934-bd03-f82ee154e90e)

**Comment by sleepy-evelyn** [comment]
> Regions Unexplored has a slight "incompat" with [snow real magic](https://modrinth.com/mod/snow-real-magic)
> ![image](https://user-images.githubusercontent.com/17211100/268482874-5222d28e-1807-4934-bd03-f82ee154e90e.png)

If u want all the features for snow real magic can be enabled/disabled individually which is handy

**Comment by EvieTheOwl** [comment]
> Regions Unexplored has a slight "incompat" with [snow real magic](https://modrinth.com/mod/snow-real-magic) ![image](https://user-images.githubusercontent.com/17211100/268482874-5222d28e-1807-4934-bd03-f82ee154e90e.png)

This isn't an issue unique to Regions Un-explored. It seems to break Falling Tree's as well. See #31

**Comment by EvieTheOwl** [comment]
No issues with Promenade still but the cave generation for Regions Unexplored seems a bit aggressive. This is a redstone cave for e.g.

![2023-09-19_12 59 28](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/82a92cca-9500-401e-82fc-4329338647c5)

Might be able to fix in the config. Need to test more

**Comment by EvieTheOwl** [comment]
> No issues with Promenade still but the cave generation for Regions Unexplored seems a bit aggressive. This is a redstone cave for e.g.
> 
> ![2023-09-19_12 59 28](https://user-images.githubusercontent.com/46009144/268967525-82a92cca-9500-401e-82fc-4329338647c5.png)
> 
> Might be able to fix in the config. Need to test more

Ok this can be fixed very easily using the biome weighting within the config. Suggested weightings are considerably less than the defaults

So...
`primary weight` = 5
`secondary weight` = 3
`nether weight` = 6

Similarly changing the terrablender config will stop really small biomes spawning and increase the rate of vanilla generation

`overworld_region_size` = 4
`nether_region_size` = 3
`vanilla_overworld_region_weight` = 15
`vanilla_nether_region_weight` = 15

Seems like the sweet spot at the moment

Additionally letting profundis and spelunkery take over predominantly for cave generation is a good idea so disabling the redstone caves since they make getting redstone too easy and disabling the scorching caves since they are kinda dangerous and may be intimidating too new peeps
