### ISSUE TITLE
Add Moog's End Structures & Bigger End Cities

### ISSUE THREAD

**Issue by EvieTheOwl** [woodiertexas/unofficial-quilt-smp-the-3rd#8]
They both look great and function fine with Nullscape. I'll include some pics below

<img width="756" alt="Screenshot 2023-09-16 at 15 33 14" src="https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/852c5eaa-a8b0-4fc1-a47c-e25f83581b7d">

## In-game pictures w/ Nullscape

![image](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/75cd2db5-d7f4-4843-9ec1-a2c421f594e0)
![image](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/assets/46009144/6fbaa166-07f6-4fed-bb1e-c9d8b9a533ad)

**Comment by stantios** [comment]
Hm, the second image worries me but I don't know if that is good or bad. From what I can see, 4 end ships in one end city which means 4 elytras.

**Comment by EvieTheOwl** [comment]
> Hm, the second image worries me but I don't know if that is good or bad. From what I can see, 4 end ships in one end city which means 4 elytras.

True. Tbh I included the bigger end cities because woodiertexas was looking at it. Not too bothered myself. Love Moog's structures tho I think they fit in really well
